### ISSUE TITLE
Top of home page cut off by navbar

### ISSUE THREAD

**Issue by baronet2** [simongravelle/simongravelle.github.io#2]
Hi @simongravelle, thanks for making your website template available!

I'm noticing that when I open your [home page](https://simongravelle.github.io/index.html) on my laptop, the top part gets cut off, even if I try scrolling all the way up. See the image below.

Things look fine on a larger monitor and on my phone, so I'm guessing it has something to do with my screen size. 
For what it's worth, my display resolution is 1920 x 200 and my display settings are at the recommended 150% scale. 

I don't know much about Hugo/CSS but maybe you know how to fix this? I am hoping to make my own personal website using your template and am hoping there's an easy solution. 🙂 

Thanks!

<img width="951" alt="image" src="https://github.com/simongravelle/simongravelle.github.io/assets/60419329/5a4e79e1-00c4-4750-b997-0a5e61492238">

**Comment by simongravelle** [comment]
Hi @baronet2,
This looks bad indeed. Unfortunately I don't have much control over that, I am just using the template and don't want to bother with it. If you are cloning it for yourself, may be you can try removing the custom css in case this is what is causing the issue. Otherwise you can try contacting the people [here](https://github.com/HugoBlox/theme-academic-cv), may be they know, or may be they even fixed it already in their latest version.
Best,
Simon

**Comment by baronet2** [comment]
Thanks Simon. I'll have a look and let you know if I find an easy fix.

**Comment by baronet2** [comment]
I ended up adding these few lines to `custom.scss`. Maybe not an ideal solution but better than nothing!

```scss
@media (min-width: 981px) {
  .page-body {
    padding-top: 150px;
  }
}
```
